name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: ballerina-platform/ballerina-action@master
        with:
          args: 
            build --sticky
      - name: Run Tests
        uses: ballerina-platform/ballerina-action@master
        with:
            args:
                test --test-report --code-coverage --coverage-format=xml 
      - name: Upload Test Report
        uses: codecov/codecov-action@v3
